### ISSUE TITLE
Install a PostgreSQL Web Interface on the Server

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-website#12]
It would be nice to easily access the database through a secure web interface instead of always using the command line interface. For the issue to be deemed resolved, the following tasks must be completed:
- [x] research options for PostgreSQL web interfaces
- [x] decide on a web interface to use
- [ ] install the web interface on our server
- [ ] update our documentation with installation instructions

**Comment by basimr** [comment]
When I created this issue, I planned to install phpPgAdmin on the server which provides a web interface to the production Postgres database.

However, I realized it would be better for each developer to use their preferred Postgres client for accessing the production database. That way, developer can access both the production database and the development database running on their machine simultaneously on their local client.

Either way of accessing the production database requires using an SSH tunnel anyway.

**Comment by ali-ramadhan** [comment]
Sounds good. Not sure how much I'll be accessing the server but I'd also
use my own client. Less server clutter too.
