### ISSUE TITLE
Some JavaScript stubs are not valid JavaScript

### ISSUE THREAD

**Issue by BinaryFissionGames** [project-lovelace/lovelace-website#137]
See, for instance, [ada_lovelaces_note_g.js](https://github.com/project-lovelace/lovelace-website/blob/main/src/static/code_stubs/javascript/ada_lovelaces_note_g.js). This code will not run since the variables aren't defined using `let` or `var` before use, and the syntax for assignment/returning looks like Python syntax (improper use of the `,` operator). This issue is also present in some of the other JavaScript stubs.

**Comment by ali-ramadhan** [comment]
Thanks for pointing this out!

Indeed I'm a Javascript noob haha but it's definitely no excuse to be misleading others by writing bad Javascript.

Will look into cleaning up the Javascript code stubs. If you have the time we would love your help!

**Comment by BinaryFissionGames** [comment]
I'll take a look at cleaning the JS stubs tomorrow. Unless you think I should do otherwise, I'll update the relevant ones to work assuming [the list issue](https://github.com/project-lovelace/lovelace-engine/issues/85) gets fixed on the engine side.

**Comment by ali-ramadhan** [comment]
Sounds good! I'll have a look at https://github.com/project-lovelace/lovelace-engine/issues/85 in the mean time.
