### ISSUE TITLE
JavaScript stubs inconsistent with var vs let

### ISSUE THREAD

**Issue by BinaryFissionGames** [project-lovelace/lovelace-website#138]
Some of the JavaScript code stubs use `var` to declare variables, while other use `let` to declare variables. These should probably be consistent between stubs (I'd advocate for `let` over `var`, but either way it should be consistent).

**Comment by ali-ramadhan** [comment]
Ah good catch! We should switch to `let` as part of cleaning up the Javascript code stubs (+ #137). I'll be sure to use `let` in any future Javascript code stubs.

**Comment by BinaryFissionGames** [comment]
Fixed with #144
