### ISSUE TITLE
Code editor not resizable in Chrome

### ISSUE THREAD

**Issue by tiitlan** [project-lovelace/lovelace-website#139]
Can't resize the code editor in Chrome 90. Works correctly in latest Edge tho.

Also, related: currently code editor width is restricted by side design. Would be nice if I could resize it as wide as reasonable.

**Comment by Vismai-Khanderao** [comment]
I'm on Chrome 90, and I can extend the code editor vertically, and similarly in edge too. Is this occurring on a specific problem or is it a site wide issue for you?

**Comment by tiitlan** [comment]
I can't reproduce this today anymore. Could have been a fluke on my end. Thanks!
