### ISSUE TITLE
Renew SSL certificate

### ISSUE THREAD

**Issue by ali-ramadhan** [project-lovelace/lovelace-website#21]
The [projectlovelace.net](https://projectlovelace.net/) SSL certificate expires on May 26 while the [projectlovelace.net](https://discourse.projectlovelace.net/) one expires on June 18.

**Comment by benallan** [comment]
Looks like both of these certificates have been updated already, so maybe this issue should be closed?

**Comment by ali-ramadhan** [comment]
True, don't remember doing it but maybe it happened automatically. Either way, closing.
