### ISSUE TITLE
Create documentation for new developers

### ISSUE THREAD

**Issue by basimr** [project-lovelace/lovelace-website#8]
For this issue to be deemed resolved, the following tasks must be completed:
- [x] document environment setup
- [ ] document PyCharm setup
- [ ] document common development procedures (like updating requirements)

**Comment by ali-ramadhan** [comment]
Just a note that I moved to conda virtual environments instead of pip environments. I can explain why I think it was a good choice but might be relevant for this documentation.

Not sure why PyCharm setup is relevant here?
